### ISSUE TITLE
kn-watch not fetching configmap details

### ISSUE THREAD

**Issue by faisalchishtii** [ScarletTanager/configmap-watcher-example#1]
When I try to hit the endpoint, it is giving me an empty value:

```
<<K9s-Shell>> Pod: watcher/watcher | Container: watcher 
/ # 
/ #  wget localhost:8080/config
Connecting to localhost:8080 (127.0.0.1:8080)
saving to 'config'
config               100% |******************************************************************************************************************************|    24  0:00:00 ETA
'config' saved
/ # 
/ #  cat config 
{"current_endpoint": ""}/ # 
/ # 
```

I picked your changes as is, build image and deployed.

Configmap is also present.

```
$ kubectl get cm clusters-config 
NAME              DATA   AGE
clusters-config   6      32m
```

Do you know what I may be doing wrong here?

**Comment by ScarletTanager** [comment]
@faisalchishtii I haven't looked at this code since I first wrote it, but I'm pretty sure it will have an empty value until you update the configmap.  The `InformedWatcher` watches for events on the configmap - and if the configmap is already there,  there won't be an events to trigger the callback until you modify it.  Try modifying the configmap (change the endpoint value) while the application is running, then curl the endpoint again (`wget` to retrieve a single line seems...excessive?).  Alternatively, start the app and *then* create the configmap - I *think* that will work, but I haven't played with this in a while.  I honestly don't really use the `knative` stuff in my own code - I use my own watcher implementation (which is really just an `Observer` pattern), if I need to write this kind of stuff.

**Comment by faisalchishtii** [comment]
@ScarletTanager Thanks for the response. It still replies empty or the initial value even after the configmap is updated. I used wget coz curl was somehow not available in the environment I was trying in. Do you have a resource for implementing watcher logic? I am new to golang and looking for resources/documentation.

**Comment by ScarletTanager** [comment]
@faisalchishtii I wrote a pair of blog posts that go with this repository:
[This one](https://medium.com/itnext/working-with-kubernetes-configmaps-part-1-volume-mounts-f0ace283f5aa) and [this one](https://medium.com/itnext/working-with-kubernetes-configmaps-part-2-watchers-b6dd0e583d71).  This repo is mostly the code I wrote for those posts.  See if that helps you get started.
